FROM python:3.12-trixie AS builder

ARG VITE_COOKIE_DOMAIN=localhost
ENV VITE_COOKIE_DOMAIN=${VITE_COOKIE_DOMAIN}

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install make nodejs npm -y

RUN pip install uv
RUN make install_backend

RUN mkdir -p ./src/backend/base/langflow/frontend/
RUN cd ./src/frontend && npm install && npm run build
RUN cp -r ./src/frontend/build/* ./src/backend/base/langflow/frontend/

CMD ["uv", "run", "langflow", "run", "--port", "8000", "--host", "0.0.0.0", "--env-file", "env_config/.user_auth_sqlite_production.env"]